version: '2'

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    networks:
      - app-tier
    environment:
      CASSANDRA_USER: "casandra"
      CASSANDRA_PASSWORD: "cassandra"
  load:
    build:
      context: ./manager
    image: "manager:latest"
    networks:
      - app-tier
  save:
    build:
      context: ./reader
    image: "reader:latest"
    networks:
      - app-tier
