version: '2'

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    networks:
      - app-tier
    environment:
      CASSANDRA_USER: "casandra"
      CASSANDRA_PASSWORD: "cassandra"
  myapp:
    image: 'YOUR_APPLICATION_IMAGE'
    networks:
      - app-tier
