spring:
  datasource:
    url: jdbc:postgresql://${pg_ip}:5432/postgres
    username: postgres
    password: ${postgres_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
